### PR TITLE
Add support for cyrillic render to HTML

### PR DESCRIPTION
**Pull request by ZXByteman**
Hi Ali,

There is a bit rough implementation for cyrillic support in html render. Oprion "cyrillic" was added, character set is Cyrillic G0 Set - Option 2 (Russian/Bulgarian).

Regards,
Alexander

### CODE REVIEW

**Comment by ZXByteman** [comment]
I've forgot to mention that in this fix I've also submitted a change to header render, I've shifted page number one letter to the left because on many services this page number was "glued" to the header title. Like this:

image

**Comment by ali1234** [comment]
The thing with "P100" is actually a bug. Last commit to that line broke it.

The rest of this I feel should be implemented in a way that allows to easily add more code pages. Probably by putting all the code pages into a dict and selecting one from the CLI.

**Comment by ZXByteman** [comment]
Hi Ali,

I've made an update to "cyrillic" branch. Now "--cyrillic" switch is replaced with "--localcodepage" where codepage should be passed as string. Character set g0 was rearranged as a dict with "default" charset used as before and "cyr" charset used for "localcodepage". Polish, German etc. codepages could be added to have support for printing them to HTML.

Regards,
Alexander

**Comment by ali1234** [comment]
Thanks!

It might be after Christmas before I can properly look at this and merge it.

**Comment by ZXByteman** [comment]
Thank you, I'm looking forward to it :)

**Comment by ZXByteman** [comment]
Hi Ali,

Let me kindly remind about my pull request 🙂

Thanks,
Alexander

**Comment by ali1234** [comment]
Why is the default `None` instead of `'default'`? Wouldn't that make it much easier?

**Comment by ali1234** [comment]
Merging this as-is for now. I squashed the letter fix.

**Pull request closed without merging**
